import type { Config } from "tailwindcss";

// Theme ported from design-templates/landing.html (Stitch Tailwind CDN config).
const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface": "#dfe2f2",
        "dashboard-accent": "#2563EB",
        "surface-container-high": "#262a36",
        "ink-900": "#0B1226",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-container-lowest": "#0a0e19",
        "outline-variant": "#424754",
        "primary-fixed-dim": "#adc6ff",
        "on-tertiary": "#472a00",
        "on-primary": "#002e6a",
        "on-secondary": "#68000a",
        "error-container": "#93000a",
        "surface-container-highest": "#303441",
        p2: "#CA8A04",
        primary: "#adc6ff",
        "secondary-container": "#a40217",
        "primary-container": "#4d8eff",
        "tertiary-container": "#ca8100",
        "on-tertiary-container": "#3e2400",
        cream: "#F4EFE4",
        "surface-variant": "#303441",
        surface: "#0f131e",
        background: "#0f131e",
        "surface-bright": "#353946",
        "secondary-fixed-dim": "#ffb3ad",
        "on-surface-variant": "#c2c6d6",
        "surface-dim": "#0f131e",
        "on-background": "#dfe2f2",
        "inverse-primary": "#005ac2",
        p1: "#EA580C",
        error: "#ffb4ab",
        "ink-800": "#131C38",
        "on-secondary-fixed-variant": "#930013",
        tertiary: "#ffb95f",
        "on-secondary-container": "#ffaea8",
        "on-error": "#690005",
        "ink-950": "#070B16",
        secondary: "#ffb3ad",
        "on-tertiary-fixed-variant": "#653e00",
        p0: "#B91C1C",
        "on-primary-fixed": "#001a42",
        "tertiary-fixed": "#ffddb8",
        "secondary-fixed": "#ffdad7",
        "primary-fixed": "#d8e2ff",
        "text-dim": "#94A3B8",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#2c303c",
        "on-tertiary-fixed": "#2a1700",
        "text-light": "#F8FAFC",
        outline: "#8c909f",
        "surface-container-low": "#171b27",
        "surface-tint": "#adc6ff",
        "on-primary-fixed-variant": "#004395",
        p3: "#475569",
        "inverse-surface": "#dfe2f2",
        "on-primary-container": "#00285d",
        "cream-dim": "#E5DEC9",
        "surface-container": "#1b1f2b",
        "on-secondary-fixed": "#410004",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-md": "1rem",
        margin: "2rem",
        "margin-mobile": "1.25rem",
        "gutter-mobile": "1rem",
        "space-lg": "1.5rem",
        gutter: "1.5rem",
        "space-xs": "0.25rem",
        "space-xl": "2.5rem",
        "space-sm": "0.5rem",
      },
      fontFamily: {
        mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "monospace"],
        "mono-lg": ["JetBrains Mono"],
        "headline-lg": ["Space Grotesk"],
        "body-md": ["Inter"],
        "headline-md": ["Space Grotesk"],
        "mono-md": ["JetBrains Mono"],
        "stamp-badge": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "mono-sm": ["JetBrains Mono"],
        "headline-sm": ["Space Grotesk"],
        "display-hero-mobile": ["Space Grotesk"],
        "display-hero": ["Space Grotesk"],
        "headline-lg-mobile": ["Space Grotesk"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "mono-lg": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "mono-md": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "500" }],
        "stamp-badge": ["14px", { lineHeight: "16px", letterSpacing: "0.15em", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "mono-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
